#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color	"#11121d"
bspc config focused_border_color "#a0b1d6"
bspc config ignore_ewmh_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a firefox desktop='^1' state=tiled follow=on
bspc rule -a discord desktop='^5' state=tiled
bspc rule -a Scratchterm sticky=on state=floating hidden=on
bspc rule -a Cwdterm sticky=on state=floating

alacritty --class "scratchterm","Scratchterm" &
picom --experimental-backends &
exec /home/rade/.config/polybar/launch.sh &
[ ! -s ~/.config/mpd/pid ] && mpd
# hsetroot -cover ~/Pictures/wallpaper.png &
setbg &
remaps &
dunst &
sleep 10 && pidof -s onedrive_tray || onedrive_tray &

